[versions]
versionCode = "1"
versionName = "1.0.0"

compileSdk = "33"
targetSdk = "33"
minSdk = "24"

releaseMinifyEnabled = "true"

kotlin = "1.8.10"
gradle = "7.4.1"

retrofit = "2.9.0"
httplogginInterceptor = "4.10.0"

room = "2.5.0"

spotify = "2.0.2"

composeCompiler = "1.4.4"
composeBom = "2023.03.00"

junit = "4.+"
testJunit = "1.1.5"
testEspresso = "3.5.1"

lifecycle = "2.6.1"

[libraries]

androidx-compose-activity = "androidx.activity:activity-compose:1.3.1"
androidx-compose-ui-ui = "androidx.compose.ui:ui:1.0.5"
androidx-compose-navigation = "androidx.navigation:navigation-compose:2.4.0-alpha10"
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling-debug = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }

androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-loggerInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "httplogginInterceptor" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-rxjava3 = { module = "androidx.room:room-rxjava3", version.ref = "room" }
room-guava = { module = "androidx.room:room-guava", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }

junit = { module = "junit:junit", version.ref = "junit" }
junit-junit = { module = "androidx.test.ext:junit", version.ref = "testJunit" }
junit-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "testEspresso" }

plugin-android = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
plugin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

spotify = { module = "com.spotify.android:auth", version.ref = "spotify" }

[bundles]

unitTest = ["junit", "junit-junit"]
instrumentationTest = ["junit", "junit-junit", "junit-espresso"]