[versions]
versionCode = "1"
versionName = "1.0.0"

compileSdk = "33"
targetSdk = "33"
minSdk = "24"

releaseMinifyEnabled = "true"

kotlin = "1.8.0"
gradle = "7.4.1"

retrofit = "2.9.0"
httplogginInterceptor = "4.10.0"

compose = "1.1.0"
composeActivity = "1.3.0"

junit = "4.+"
testJunit = "1.1.5"
testEspresso = "3.5.1"

[libraries]

plugin-android = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
plugin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-loggerInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "httplogginInterceptor" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }

junit = { module = "junit:junit", version.ref = "junit" }
junit-junit = { module = "androidx.test.ext:junit", version.ref = "testJunit" }
junit-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "testEspresso" }

[bundles]

retrofit = ["retrofit-core", "retrofit-gson", "retrofit-loggerInterceptor"]

compose = ["compose-ui", "compose-material", "compose-runtime", "compose-activity"]

unitTest = ["junit", "junit-junit"]
instrumentationTest = ["junit", "junit-junit", "junit-espresso"]